const CategoryTypes = {
  GET__CATEGORIES   : 'GET_CATEGORIES',
  GET_CATEGORY_SUBCATEGORIES : 'GET_CATEGORY_SUBCATEGORIES',
  SET_LOADING : 'SET_LOADING',
  DONE_LOADING: 'DONE_LOADING',
}

export default CategoryTypes;
