const productTypes = {
  GET_ALL_PRODUCTS : 'GET_ALL_PRODUCTS',
  GET_PRODUCT_SUBCATEGORY : 'GET_PRODUCT_SUBCATEGORY',
  SET_LOADING : 'SET_LOADING',
  DONE_LOADING: 'DONE_LOADING',
  ADD_PRODUCT : 'ADD_PRODUCT',
}

export default productTypes;
